name: https://stage-collector.foci.life/

concurrency: stage

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-18.04
    environment: stage
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'mandrel-22.1.0.0-Final'
          java-version: '17'
      - name: Package
        # We don't want the native executable to be built wth test profile (e.g. including superfluous test resources)
        run: |
          ./mvnw clean verify -Pnative -Dquarkus-profile=test && ./mvnw package -DskipTests -Pnative
      - name: Deploy
        if: success()
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          echo "$KNOWN_HOSTS" > ~/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          scp -o UserKnownHostsFile=~/known_hosts ./target/collector-*-runner collector@${{ secrets.SERVER_ADDRESS }}:/home/collector/stage/collector.deploy
          ssh -o UserKnownHostsFile=~/known_hosts collector@${{ secrets.SERVER_ADDRESS }} "sudo systemctl restart stage-collector.foci.life"
          echo "Version $(git describe --tags --always) should be on https://stage-collector.foci.life/"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports-${{ runner.os }}
          path: |
            target/surefire-reports
