name: https://stage-collector.foci.life/

concurrency: stage

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  LANG: en_US.UTF-8
  BUILDER_IMAGE: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21

jobs:
  deployment:
    runs-on: ubuntu-22.04
    environment: stage
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-node@v4
        with:
          node-version: '18.1.0'
      - name: Setup yarn
        run: npm install -g yarn@1.22.17
      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Package
        # We don't want the native executable to be built wth test profile (e.g. including superfluous test resources)
        run: >-
          ./mvnw clean -Dui.deps -Dui verify -Pnative -Dquarkus.profile=test
          -Dquarkus.native.container-build=true
          -Dquarkus.native.builder-image=${BUILDER_IMAGE} &&
          ./mvnw -Dui.deps -Dui package -DskipTests -Pnative
          -Dquarkus.native.container-build=true -Dquarkus.profile=stage
          -Dquarkus.native.builder-image=${BUILDER_IMAGE}
      - name: Deploy
        if: success()
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          echo "$KNOWN_HOSTS" > ~/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "$SSH_KEY"
          scp -o UserKnownHostsFile=~/known_hosts ./target/collector-*-runner collector@${{ secrets.SERVER_ADDRESS }}:/home/collector/stage/collector.deploy
          ssh -o UserKnownHostsFile=~/known_hosts collector@${{ secrets.SERVER_ADDRESS }} "sudo systemctl restart stage-collector.foci.life"
          ssh -o UserKnownHostsFile=~/known_hosts collector@${{ secrets.SERVER_ADDRESS }} "sudo systemctl status stage-collector.foci.life"
          echo "Version $(git describe --tags --always) should be on https://stage-collector.foci.life/"
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ runner.os }}
          path: |
            target/surefire-reports
